//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwainDirect.Scanner {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class lang_es_ES {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang_es_ES() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TwainDirect.Scanner.lang_es_ES", typeof(lang_es_ES).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quieres cerrar &apos;TWAIN Direct: TWAIN Bridge&apos;?.
        /// </summary>
        public static string errCloseTwainBridge {
            get {
                return ResourceManager.GetString("errCloseTwainBridge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localizando escaners....
        /// </summary>
        public static string errLookingForScanners {
            get {
                return ResourceManager.GetString("errLookingForScanners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lo sentimos, no tenemos un administrador de Cloud para este Cloud..
        /// </summary>
        public static string errNoCloudManager {
            get {
                return ResourceManager.GetString("errNoCloudManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontraron escaners..
        /// </summary>
        public static string errNoScannersFound {
            get {
                return ResourceManager.GetString("errNoScannersFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fallo al registrar el escaner en el Cloud. Mensaje de error &apos;{0}&apos;.
        /// </summary>
        public static string errRegisterCloudScanner {
            get {
                return ResourceManager.GetString("errRegisterCloudScanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quieres seleccionar un controlador TWAIN?  Si es así, asegurate que este conectado y encendido.
        /// </summary>
        public static string errRegisterTwainDriver {
            get {
                return ResourceManager.GetString("errRegisterTwainDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo usar el escaner seleccionado.  Asegurate que este encendido y conectado.
        /// </summary>
        public static string errUnableToUseScanner {
            get {
                return ResourceManager.GetString("errUnableToUseScanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrar Cloud....
        /// </summary>
        public static string strButtonCloudRegisterEllipsis {
            get {
                return ResourceManager.GetString("strButtonCloudRegisterEllipsis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestionar Cloud....
        /// </summary>
        public static string strButtonManageCloudEllipsis {
            get {
                return ResourceManager.GetString("strButtonManageCloudEllipsis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualizar lista de escaners.
        /// </summary>
        public static string strButtonRefreshScannersList {
            get {
                return ResourceManager.GetString("strButtonRefreshScannersList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar escaner....
        /// </summary>
        public static string strButtonRegisterEllipsis {
            get {
                return ResourceManager.GetString("strButtonRegisterEllipsis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar.
        /// </summary>
        public static string strButtonStart {
            get {
                return ResourceManager.GetString("strButtonStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parar.
        /// </summary>
        public static string strButtonStop {
            get {
                return ResourceManager.GetString("strButtonStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestión Local....
        /// </summary>
        public static string strButtonTwainLocalManagerEllipsis {
            get {
                return ResourceManager.GetString("strButtonTwainLocalManagerEllipsis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aviso en TWAIN local y TWAIN Cloud cuando la aplicación se inicia.
        /// </summary>
        public static string strCheckboxAdvertise {
            get {
                return ResourceManager.GetString("strCheckboxAdvertise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enseñar mensaje de confirmación cuando se empieza a escanear.
        /// </summary>
        public static string strCheckboxConfirmation {
            get {
                return ResourceManager.GetString("strCheckboxConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conectar al abrir la aplicación.
        /// </summary>
        public static string strCheckboxConnectOnStartup {
            get {
                return ResourceManager.GetString("strCheckboxConnectOnStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ejecute este programa cuando inicie sesión.
        /// </summary>
        public static string strCheckboxRunOnLogin {
            get {
                return ResourceManager.GetString("strCheckboxRunOnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automaticamente ejecutar &apos;npm start&apos; para twain-cloud-express.
        /// </summary>
        public static string strCheckboxStartNpm {
            get {
                return ResourceManager.GetString("strCheckboxStartNpm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TWAIN Direct: TWAIN Bridge.
        /// </summary>
        public static string strFormMainTitle {
            get {
                return ResourceManager.GetString("strFormMainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controlador:.
        /// </summary>
        public static string strLabelCurrentDriver {
            get {
                return ResourceManager.GetString("strLabelCurrentDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre:.
        /// </summary>
        public static string strLabelCurrentNote {
            get {
                return ResourceManager.GetString("strLabelCurrentNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dispositivo Cloud:.
        /// </summary>
        public static string strLabelRegisteredDevice {
            get {
                return ResourceManager.GetString("strLabelRegisteredDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paso 1: Selecciona el controlador de TWAIN para tu escaner..
        /// </summary>
        public static string strLabelStep1 {
            get {
                return ResourceManager.GetString("strLabelStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paso  2: Configura tu sistema para soportar TWAIN en local (opcional)..
        /// </summary>
        public static string strLabelStep2 {
            get {
                return ResourceManager.GetString("strLabelStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paso 3: Registrar con TWAIN Cloud (opcional)..
        /// </summary>
        public static string strLabelStep3 {
            get {
                return ResourceManager.GetString("strLabelStep3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Acerca de.
        /// </summary>
        public static string strMenuAbout {
            get {
                return ResourceManager.GetString("strMenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E&amp;xit....
        /// </summary>
        public static string strMenuExit {
            get {
                return ResourceManager.GetString("strMenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Abrir.
        /// </summary>
        public static string strMenuShowConsole {
            get {
                return ResourceManager.GetString("strMenuShowConsole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar el controlador de escaner:.
        /// </summary>
        public static string strSelectScannerDriver {
            get {
                return ResourceManager.GetString("strSelectScannerDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Una nota o un alias para tu escaner:.
        /// </summary>
        public static string strSetNote {
            get {
                return ResourceManager.GetString("strSetNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un programa que permite que las aplicaciones TWAIN Direct se comuniquen con escáneres compatibles con controladores TWAIN..
        /// </summary>
        public static string strTextAbout {
            get {
                return ResourceManager.GetString("strTextAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloud seleccionado:.
        /// </summary>
        public static string strTextCurrentCloud {
            get {
                return ResourceManager.GetString("strTextCurrentCloud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listado de escáneres registrados... (espere la lista).
        /// </summary>
        public static string strTextListingScannersBegin {
            get {
                return ResourceManager.GetString("strTextListingScannersBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listado completo....
        /// </summary>
        public static string strTextListingScannersEnd {
            get {
                return ResourceManager.GetString("strTextListingScannersEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay escaners registrados....
        /// </summary>
        public static string strTextNoScannersRegistered {
            get {
                return ResourceManager.GetString("strTextNoScannersRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En Aceptar, el programa se minimizará en la bandeja del sistema, haga clic con el botón derecho en su icono para acceder a él. Al cancelar este cuadro de diálogo, se cerrará..
        /// </summary>
        public static string strTextNotClosing {
            get {
                return ResourceManager.GetString("strTextNotClosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fallo al iniciar &apos;npm&apos;.
        /// </summary>
        public static string strTextNpmFailed {
            get {
                return ResourceManager.GetString("strTextNpmFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciando &apos;npm start&apos;, esperaremos 15 minutos a que arranque..
        /// </summary>
        public static string strTextStartNpm {
            get {
                return ResourceManager.GetString("strTextStartNpm", resourceCulture);
            }
        }
    }
}
